blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/rishabh100
    about: You can join our Discord.
  - name: Github
    url: https://github.com/Rishabh672003
    about: github profile

